version: "3"
services:
  apiService:
    image: leonardoduarte1305/api-transportes-service:authOk
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - transportes-network
    depends_on:
      - mysql-compose
      - keycloak

  mysql-compose:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=apiTransportes
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=senhaSegura
    volumes:
      - mysqlCompose
    networks:
      - transportes-network

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: always
    networks:
      - transportes-network
    depends_on:
      - postgres
      - mysql-compose

  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
