version: "3"
services:
  frontend:
    image: docker.io/leonardoduarte1305/stm-frontend:01
    ports:
      - 4200:80
    env_file:
      - .env
    restart: always
    networks:
      - stm-network
    depends_on:
      - backend

  backend:
    image: docker.io/leonardoduarte1305/api-transportes-service:noAuth #27-04
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    networks:
      - stm-network
    depends_on:
      - keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: always
    networks:
      - stm-network

networks:
  stm-network:
