version: "3"
services:
  mysql-compose:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - compose.env
    volumes:
      - mysqlCompose
    restart: always
    networks:
      - transportes-network

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "8080:8080"
    env_file:
      - compose.env
    restart: always
    networks:
      - transportes-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - compose.env
    restart: always
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
