version: "3"
services:
  api-transportes:
    image: leonardoduarte1305/api-transportes-service:pdf
    ports:
      - 8080:8080
    env_file:
      - compose.env
    restart: always
    networks:
      - transportes-network
    depends_on:
      - postgresql
      - keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - compose.env
    restart: always
    networks:
      - transportes-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    env_file:
      - compose.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
