version: "3"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    env_file:
      - variaveis_de_ambiente.env
    volumes:
      - mysqlCompose
    networks:
      - transportes-network

  postgres:
    image: postgres
    env_file:
      - variaveis_de_ambiente.env
    restart: always
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - variaveis_de_ambiente.env
    restart: always
    depends_on:
      - postgres
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
