version: "3"
services:
  mysql-compose:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - compose.env
    volumes:
      - mysqlCompose
    restart: always
    networks:
      - transportes-network

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - compose.env
    restart: always
    networks:
      - transportes-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    env_file:
      - compose.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

  nexus:
    image: sonatype/nexus3:3.42.0
    user: nexus
    ports:
      - '8081:8081'
    volumes:
      - nexus-data:/nexus-data
      - sonatype-work:/sonatype-work
    restart: always
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
  nexus-data:
  sonatype-work:
