version: "3"
services:
  apiService:
    image: leonardoduarte1305/api-transportes-service:externas
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=senhaSegura
      - MYSQL_DATASOURCE_URL=jdbc:mysql://mysql-compose:3306/apiTransportes?useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - transportes-network
    depends_on:
      - mysql-compose
    links:
      - mysql-compose

  mysql-compose:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=apiTransportes
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=senhaSegura
    volumes:
      - mysqlCompose
    networks:
      - transportes-network

  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgresCompose:/var/lib/postgresql
      - postgresCompose-data:/var/lib/postgresql/data
    networks:
      - transportes-network

  keycloak:
    image: docker.io/bitnami/keycloak:20
    ports:
      - "80:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    networks:
      - transportes-network

networks:
  transportes-network:

volumes:
  mysqlCompose:
  postgresCompose:
  postgresCompose-data:
