INSERT INTO `motorista`
VALUES (1, '982196943', 'santacruz.pedro@example.com', 'Regina Michele Pena Jr.'),
       (2, '502855095', 'henrique.delatorre@example.com', 'Helena Amanda Matias Jr.'),
       (3, '445023553', 'miranda.guerra@example.net', 'Carolina Abril Martines'),
       (4, '330082847', 'desouza.joana@example.org', 'Gabriela Amélia Fernandes'),
       (5, '867274084', 'rosa.laura@example.org', 'Isabella Pâmela Rangel'),
       (6, '725406966', 'hverdugo@example.net', 'Dr. Jerônimo Tomás Bittencourt Jr.'),
       (7, '677786629', 'pereira.everton@example.com', 'Sr. Bruno Leandro Meireles Filho'),
       (8, '085918400', 'sepúlveda.agustina@example.net', 'Dr. Amélia Escobar Jr.'),
       (9, '929085186', 'michele96@example.net', 'Srta. Mia Alessandra Velasques'),
       (10, '547976783', 'jcorona@example.org', 'Clara Pacheco'),
       (11, '465444808', 'luana.leon@example.com', 'Rafaela Fontes Jr.'),
       (12, '844626876', 'ypadrão@example.org', 'Norma Caldeira'),
       (13, '335034852', 'miguel.gonçalves@example.com', 'Dr. Andres Ivan Teles Filho'),
       (14, '840245296', 'emiliano25@example.com', 'Srta. Beatriz Perez'),
       (15, '827790251', 'sestrada@example.com', 'Sr. Miguel Elias Soares Neto'),
       (16, '528850635', 'suzana01@example.net', 'Dr. Alan Bittencourt'),
       (17, '540486502', 'oqueirós@example.com', 'Ian Pedro Serna'),
       (18, '725072362', 'trico@example.org', 'Sr. Eduardo Vasques Zaragoça Sobrinho'),
       (19, '389619151', 'ana.ferreira@example.com', 'Dr. Josué Tomás Molina'),
       (20, '983767210', 'fidalgo.noel@example.net', 'Manuel Bonilha da Cruz Sobrinho'),
       (21, '375790367', 'henrique.escobar@example.net', 'Sra. Melissa Salazar Sobrinho'),
       (22, '056637262', 'uchoa.thales@example.net', 'Srta. Noelí Perez Velasques'),
       (23, '710268945', 'isabel20@example.net', 'Sr. Inácio Simão Gil Filho'),
       (24, '143209165', 'vitória41@example.com', 'Paulina Camila Salas Jr.'),
       (25, '878939735', 'rocha.malena@example.com', 'Sra. Alexa Abreu'),
       (26, '947618530', 'escobar.valentin@example.net', 'Dr. Rafaela Vila Galindo Neto'),
       (27, '430329114', 'tabreu@example.com', 'Dr. Cristóvão Delatorre Corona'),
       (28, '355888716', 'bianca.darosa@example.net', 'Sra. Abgail Bittencourt'),
       (29, '510459245', 'gabriela.aranda@example.net', 'Maximiano Delatorre Ferreira'),
       (30, '628691475', 'pdelvalle@example.net', 'Isabella Ferraz Perez');

INSERT INTO `setor`
VALUES (1, 'rerum'),
       (2, 'amet'),
       (3, 'ut'),
       (4, 'fugiat'),
       (5, 'aut'),
       (6, 'adipisci'),
       (7, 'aliquid'),
       (8, 'illo'),
       (9, 'quia'),
       (10, 'enim'),
       (11, 'in'),
       (12, 'totam'),
       (13, 'similique'),
       (14, 'expedita'),
       (15, 'et'),
       (16, 'aspernatur'),
       (17, 'error'),
       (18, 'quibusdam'),
       (19, 'sit'),
       (20, 'ratione'),
       (21, 'sapiente'),
       (22, 'unde'),
       (23, 'est'),
       (24, 'eos'),
       (25, 'inventore'),
       (26, 'molestiae'),
       (27, 'laboriosam'),
       (28, 'quisquam'),
       (29, 'voluptate'),
       (30, 'velit');

INSERT INTO `veiculo`
VALUES (1, 2005, 'Schiller, Glover and Gulgowski', 'ex', 'oge-8052', 28957397881.00, '3.65'),
       (2, 2017, 'Bayer, Marvin and Durgan', 'nam', 'gxd-4691', 30403953677.00, '2.11'),
       (3, 2004, 'Gaylord and Sons', 'doloribus', 'lvz-0594', 32767602780.00, '3.37'),
       (4, 2003, 'Skiles-Schaefer', 'ut', 'knp-5182', 96896239494.00, '3.49'),
       (5, 2008, 'Swaniawski, Bins and Dare', 'eos', 'exz-3385', 39497607655.00, '2.75'),
       (6, 2004, 'Muller-Rogahn', 'quasi', 'miy-2037', 24004610671.00, '2.99'),
       (7, 2019, 'Vandervort-Schimmel', 'error', 'bne-9634', 99685115430.00, '3.96'),
       (8, 2018, 'Murphy-OKeefe', 'beatae', 'zhn-0596', 37165530477.00, '3.47'),
       (9, 2010, 'Langosh-Hilpert', 'ad', 'cqm-6287', 67289706333.00, '3.89'),
       (10, 2005, 'Koch, Rodriguez and Nicolas', 'fuga', 'xik-5538', 36472126778.00, '2.84'),
       (11, 2023, 'Hettinger, Boyer and Olson', 'vero', 'dei-9097', 9489075174.00, '2.39'),
       (12, 2009, 'Pouros Ltd', 'laborum', 'lwn-9526', 85176199824.00, '2.56'),
       (13, 2008, 'Gusikowski-Hoeger', 'necessitatibus', 'mok-5407', 92574837545.00, '3.05'),
       (14, 2021, 'Flatley, Howell and Hettinger', 'ratione', 'tly-0309', 93237437161.00, '3.49'),
       (15, 2007, 'Hermiston and Sons', 'necessitatibus', 'waa-2223', 28631294778.00, '3.41'),
       (16, 2017, 'Powlowski, OReilly and McGlynn', 'tempora', 'crz-9504', 76692282473.00, '2.08'),
       (17, 2011, 'Herzog, Hegmann and Gutmann', 'aut', 'qnl-8387', 2746482369.00, '3.58'),
       (18, 2017, 'Bailey Group', 'est', 'rmp-9481', 60585701447.00, '2.32'),
       (19, 2007, 'Pfannerstill, Schinner and Gutkowski', 'qui', 'hry-6551', 32948896962.00, '3.26'),
       (20, 2017, 'Roob-Nicolas', 'consequuntur', 'hjo-0552', 35863056810.00, '3.05');

INSERT INTO `sede`
VALUES (1, '77643-901', 'Funkshire', 'Qui facere.', 661, 'Veritatis magnam eum earum.', '52011 Rippin Street Suite 636',
        'ES'),
       (2, '05096-986', 'Port Marcel', 'Enim et reiciendis.', 674, 'Ea voluptas enim magni.', '4508 Aditya Ramp', 'RR'),
       (3, '91790-643', 'Alexysberg', 'Mollitia sed dolore.', 1116, 'Et voluptas soluta sint eos possimus.',
        '206 Alberto Point', 'PI'),
       (4, '33077-969', 'East Rebeka', 'Quia non autem.', 1042, 'Architecto voluptatem explicabo quod aliquid.',
        '843 Callie Via Suite 218', 'MS'),
       (5, '90208-610', 'Verlietown', 'Et odit.', 1839, 'Dolor quidem qui numquam cupiditate.', '652 Cecile Loop',
        'RN'),
       (6, '86594-030', 'Alfonsotown', 'Ea ducimus id.', 1566, 'Totam ut consequuntur est.',
        '73004 Herman Haven Apt. 291', 'AM'),
       (7, '99294-444', 'New Kallieville', 'Quos soluta voluptatum.', 1429,
        'Sit distinctio tempora excepturi doloribus corporis et.', '7728 Elena Valley', 'DF'),
       (8, '62441-003', 'North Rodolfo', 'Delectus nulla.', 250, 'Cumque excepturi amet velit sint doloremque at.',
        '06322 Yost Drive', 'CE'),
       (9, '93052-202', 'Emmyshire', 'Ut et veniam.', 1646, 'Tempora atque quidem sed ducimus sed.', '0181 Graham Dale',
        'RR'),
       (10, '21629-143', 'West Zachery', 'Facere tempora vitae.', 1958, 'Excepturi porro qui aliquid.',
        '300 Keith Shoals Apt. 141', 'RJ'),
       (11, '78372-448', 'McGlynnmouth', 'Fuga odit in.', 1103, 'Natus non similique eos atque sit.',
        '38966 Albin Green', 'BA'),
       (12, '51654-454', 'Beierton', 'Quo aspernatur fugiat.', 740, 'Voluptas error eos veritatis cupiditate.',
        '0087 Joelle Junction', 'RR'),
       (13, '05237-498', 'Strosinburgh', 'Excepturi ut quia.', 1898, 'Consectetur non illo id consequatur qui.',
        '26434 Federico Manor Suite 563', 'PB'),
       (14, '71286-365', 'Lake Raquel', 'Quasi quidem.', 182, 'Quam enim aut sit.', '4089 Billie Ramp Apt. 835', 'AL'),
       (15, '99705-773', 'New Monroe', 'Itaque distinctio.', 1576, 'Natus necessitatibus dolore sint impedit atque.',
        '0666 Reinger Parkways', 'RR'),
       (16, '41721-689', 'Port Leola', 'Aperiam aut alias.', 50, 'Vero incidunt et dolores est velit illo.',
        '119 Christina Pike', 'RJ'),
       (17, '38572-994', 'Ronaldoborough', 'Voluptate quo voluptatem.', 1085,
        'Quia eaque similique id beatae aliquid similique.', '5284 Imogene Divide', 'MG'),
       (18, '19483-915', 'Framiland', 'Tempora debitis tempore.', 1032, 'Error voluptas ea adipisci.',
        '867 Bashirian Fords Apt. 962', 'PI'),
       (19, '06507-637', 'Batzton', 'Non aperiam cumque.', 1893,
        'Et excepturi similique magni iste asperiores expedita.', '3341 Mariah Ridges', 'AL'),
       (20, '09855-518', 'Dedrictown', 'Et laudantium.', 504, 'Esse ab voluptas temporibus.',
        '08521 Jayne Fall Suite 353', 'SE'),
       (21, '23368-797', 'Lake Einarshire', 'Id deleniti ullam.', 730, 'Fugit doloribus assumenda quam.',
        '03999 Caleigh Street Suite 759', 'PE'),
       (22, '88018-147', 'Heidenreichhaven', 'Officiis rerum unde.', 1837, 'Voluptates suscipit rerum aut explicabo.',
        '124 Cassin Drive', 'RJ'),
       (23, '03739-535', 'Port Bethany', 'Est quidem.', 1370, 'Adipisci debitis reprehenderit qui ullam minima ipsa.',
        '7642 Tate Isle', 'MA'),
       (24, '30320-275', 'South Dalemouth', 'Occaecati incidunt totam.', 1810,
        'Est laborum voluptatem et totam voluptatem.', '8149 Goldner Ports', 'AC'),
       (25, '56214-671', 'West Caleigh', 'Reprehenderit ut.', 1931, 'Porro consectetur eum aut illo aut.',
        '0455 Petra Alley', 'PR'),
       (26, '39055-570', 'North Duncanside', 'Aperiam alias.', 804,
        'Explicabo voluptatem vitae repudiandae mollitia ut deleniti.', '4341 Parisian Prairie Apt. 088', 'PR'),
       (27, '91834-519', 'Zulaufhaven', 'Ducimus ratione modi.', 952, 'Quis laborum ipsum et.',
        '801 Michelle Burg Apt. 674', 'RJ'),
       (28, '30268-597', 'Port Goldaland', 'Sint dolor et.', 424, 'Qui placeat consequatur quasi.', '854 Adrien Knolls',
        'RS'),
       (29, '27572-381', 'Kutchport', 'Recusandae est.', 803, 'Distinctio repellendus occaecati aperiam aut assumenda.',
        '8478 Alexandra Place', 'MA'),
       (30, '63984-316', 'Wintheiserview', 'Suscipit libero velit.', 867, 'Laudantium omnis cupiditate voluptatibus.',
        '5653 Watsica Rapid Suite 352', 'RS');

INSERT INTO `material`
VALUES (1, 'Maxime excepturi iste officia unde modi qui.', 'Voluptatem illo placeat.'),
       (2, 'A qui dignissimos modi odio eligendi.', 'Qui et atque.'),
       (3, 'Saepe nobis excepturi nihil reiciendis ratione magnam.', 'Similique et.'),
       (4, 'Enim dolor ullam qui sit.', 'Error delectus.'),
       (5, 'Eum reprehenderit sequi ut inventore quia.', 'Ut ex.'),
       (6, 'Voluptatum itaque ut rerum voluptatem quia sint.', 'Ea cupiditate.'),
       (7, 'Architecto ea dolor ipsa esse totam eum.', 'Consectetur et.'),
       (8, 'Voluptatem nesciunt cupiditate nesciunt.', 'Eos hic dolor.'),
       (9, 'Quis nisi et qui.', 'Ea esse sint.'),
       (10, 'Illo explicabo quisquam earum et neque.', 'Ipsam dicta.'),
       (11, 'Illum nihil eius dolores nihil est.', 'Dignissimos consequuntur.'),
       (12, 'Quaerat dolorem perferendis dolores.', 'Eos assumenda.'),
       (13, 'In dolorem cum quae.', 'Voluptatum quibusdam mollitia.'),
       (14, 'Libero officia vitae doloribus aperiam velit natus.', 'Aut ut incidunt.'),
       (15, 'Dolorum commodi neque dolores.', 'Natus distinctio.'),
       (16, 'Qui quas maxime voluptas ea.', 'Sint cupiditate saepe.'),
       (17, 'Quam ut reiciendis molestiae totam architecto.', 'Facere animi necessitatibus.'),
       (18, 'Iusto corrupti suscipit et.', 'Autem optio.'),
       (19, 'Dignissimos et sed architecto corporis et perferendis.', 'Similique expedita.'),
       (20, 'Accusamus quae fugit numquam.', 'Est adipisci amet.'),
       (21, 'Eos corporis possimus dolores sint reiciendis tenetur.', 'Sunt tempore nisi.'),
       (22, 'Dolor eos deserunt ad praesentium tempora et adipisci.', 'Harum ducimus asperiores.'),
       (23, 'At asperiores quis illo ratione id.', 'Unde consequatur.'),
       (24, 'Ipsum iure voluptas qui dolor animi.', 'Aliquid voluptatem quo.'),
       (25, 'Inventore rerum natus quod.', 'Qui et.'),
       (26, 'Sit quaerat aut corrupti temporibus quam consequatur.', 'Rerum et.'),
       (27, 'Ea repellendus delectus at.', 'Explicabo aperiam expedita.'),
       (28, 'Corporis error sed repudiandae quibusdam officia.', 'Ex ut.'),
       (29, 'Qui dolores asperiores magni alias.', 'Pariatur cumque voluptas.'),
       (30, 'Deleniti similique ut sunt autem harum quia.', 'Ea molestiae.'),
       (31, 'Saepe magnam similique et consequatur.', 'Dolore nihil ad.'),
       (32, 'Ut rem rerum placeat aspernatur facere.', 'Exercitationem neque ea.'),
       (33, 'Aut officia perferendis pariatur maxime.', 'Mollitia facere.'),
       (34, 'Inventore ullam porro pariatur qui eum dolorem.', 'Rem et et.'),
       (35, 'Deleniti veritatis fuga tempore aut labore ipsam.', 'Quos quis et.'),
       (36, 'Nisi velit dolores et consequatur necessitatibus excepturi.', 'Accusantium ducimus voluptatem.'),
       (37, 'Voluptatem quae omnis quam alias illum beatae.', 'Quidem beatae ipsum.'),
       (38, 'Illum deleniti nihil impedit ut distinctio.', 'Quos odio cum.'),
       (39, 'In ut repellat ipsum qui.', 'Sed aliquam.'),
       (40, 'Error eaque placeat beatae qui et.', 'Facere aut.'),
       (41, 'Et autem quibusdam eos veniam.', 'Praesentium quod.'),
       (42, 'Quidem quod eum sint facilis quam sed.', 'Non vel aut.'),
       (43, 'Sint est quisquam nobis.', 'Mollitia quibusdam rerum.'),
       (44, 'Unde quam maiores deserunt.', 'Consequatur quia adipisci.'),
       (45, 'Dolores pariatur repellat itaque exercitationem voluptate voluptas.', 'Corporis consequuntur enim.'),
       (46, 'Nisi debitis et rerum veniam.', 'Voluptatibus perferendis.'),
       (47, 'Placeat alias et veritatis quia.', 'Qui quis.'),
       (48, 'Facere sit accusamus rem consequatur quo occaecati.', 'Similique minus.'),
       (49, 'Rerum praesentium laboriosam et.', 'Perferendis nulla.'),
       (50, 'Magnam est ut repellendus.', 'Reiciendis ut animi.'),
       (51, 'Expedita voluptate harum quos non.', 'Cum doloribus aut.'),
       (52, 'Exercitationem voluptate est asperiores reiciendis vitae autem.', 'Dolore aut.'),
       (53, 'Aspernatur est et in.', 'Ut tenetur dolorem.'),
       (54, 'Ipsum eaque et facere voluptatibus.', 'Et omnis.'),
       (55, 'Quia vero libero corporis numquam consequatur ullam.', 'Sed dolor occaecati.'),
       (56, 'Sunt velit qui est quod.', 'Magnam sunt.'),
       (57, 'Veritatis doloremque voluptas sequi.', 'Doloribus minus necessitatibus.'),
       (58, 'Dolorum pariatur soluta impedit et sunt.', 'Omnis enim.'),
       (59, 'Cum at quo sequi.', 'Unde autem.'),
       (60, 'Totam et eum quae molestias est voluptates.', 'Dignissimos sed quae.'),
       (61, 'Odio accusamus eum quis suscipit.', 'Est qui culpa.'),
       (62, 'Voluptates eveniet et possimus.', 'Inventore id.'),
       (63, 'Dolor laborum quod atque consequatur.', 'Iste assumenda.'),
       (64, 'Sit dolorum eum magni aut perspiciatis.', 'Consectetur aut dignissimos.'),
       (65, 'Hic distinctio eum quam.', 'Soluta quidem.'),
       (66, 'Delectus minus impedit voluptatem.', 'Culpa ipsam labore.'),
       (67, 'Perferendis libero in quis vero adipisci necessitatibus.', 'Consequatur magnam qui.'),
       (68, 'Est alias nisi quisquam quis voluptatem pariatur saepe.', 'Et nobis.'),
       (69, 'Fugit enim qui ut.', 'Voluptatem hic reprehenderit.'),
       (70, 'Laboriosam nulla ut molestias.', 'Iure fugit dolores.'),
       (71, 'Vitae dolores et odio facere sunt.', 'Qui quis minima.'),
       (72, 'Eius deleniti dolorem quis aut.', 'Voluptates eius.'),
       (73, 'Voluptatem enim velit qui.', 'Doloribus possimus.'),
       (74, 'Quis sed ea quo.', 'Aperiam saepe reiciendis.'),
       (75, 'A dolor quia suscipit.', 'Rerum sit porro.'),
       (76, 'Accusamus in libero eum voluptatibus omnis.', 'Excepturi deserunt.'),
       (77, 'Alias unde explicabo laboriosam aut.', 'Quaerat eum.'),
       (78, 'Aut exercitationem laudantium sit aut.', 'Non est.'),
       (79, 'Eos vitae impedit minus ut.', 'Voluptas corrupti ipsum.'),
       (80, 'Aliquam qui aliquid cupiditate vero ipsa aut dicta.', 'Et voluptatum.'),
       (81, 'Non a non suscipit nihil cum vel.', 'Delectus voluptates placeat.'),
       (82, 'Labore aut consequatur sapiente impedit unde dolorum.', 'Sint alias.'),
       (83, 'Quos quis sed quia.', 'Autem et.'),
       (84, 'Temporibus non quos quis consequatur occaecati.', 'Enim officiis.'),
       (85, 'Ipsam necessitatibus id rem.', 'Laboriosam accusamus eius.'),
       (86, 'Consequatur vero illum nisi optio.', 'Dolore itaque voluptas.'),
       (87, 'Dolores id voluptatibus quam quis.', 'Qui maiores.'),
       (88, 'Illo quas consectetur natus nihil enim.', 'Temporibus rerum.'),
       (89, 'Voluptas non debitis quaerat.', 'Magni aut ut.'),
       (90, 'Reiciendis est reiciendis dolorum ea natus.', 'Sequi at.'),
       (91, 'Consequuntur tenetur eum sint.', 'Porro aspernatur.'),
       (92, 'Rerum aliquid facere hic.', 'Quibusdam corporis.'),
       (93, 'Consequatur non consequatur in reiciendis qui.', 'Eum et libero.'),
       (94, 'Et iusto et aperiam sit.', 'Voluptates itaque totam.'),
       (95, 'Adipisci sed distinctio facilis.', 'Distinctio fugiat.'),
       (96, 'Optio aperiam cumque quas rerum.', 'Sed eaque cum.'),
       (97, 'Iste iste reprehenderit est magni.', 'A nihil quam.'),
       (98, 'Perferendis repellat ut eaque voluptates culpa et.', 'Eligendi reiciendis quia.'),
       (99, 'Officia sit cupiditate quis in.', 'Et voluptatem.'),
       (100, 'Saepe reprehenderit non enim ad.', 'Molestias iste doloribus.');
