INSERT INTO `motorista`
VALUES (1, '478', 'simon.gusmão@example.org', 'Sra. Tessália Perez'),
       (2, '012', 'paula.escobar@example.net', 'Sr. Leonardo Saraiva'),
       (3, '026', 'gusmão.suzana@example.com', 'Sr. Guilherme Teobaldo Grego Sobrinho'),
       (4, '671', 'mário12@example.net', 'Dr. Suzana Bezerra Sobrinho'),
       (5, '237', 'ouchoa@example.net', 'Agustina Batista Cortês Filho'),
       (6, '746', 'amélia.rico@example.net', 'Dr. Jasmin Aragão Galhardo Jr.'),
       (7, '399', 'ramos.felipe@example.com', 'Dr. Carlos Torres Sobrinho'),
       (8, '889', 'vasques.camilo@example.org', 'Luciano Cristóvão Rezende'),
       (9, '989', 'jrodrigues@example.com', 'Norma Pacheco Sobrinho'),
       (10, '461', 'ngomes@example.org', 'Sr. Jerônimo Garcia Lovato'),
       (11, '062', 'alexandre59@example.com', 'Dr. Elias Tomás Mendonça Sobrinho'),
       (12, '846', 'allison65@example.com', 'Jorge Pereira Marinho'),
       (13, '685', 'martinho10@example.net', 'Srta. Mel Jasmin Molina Sobrinho'),
       (14, '315', 'josefina56@example.com', 'Benjamin Franco Lutero Neto'),
       (15, '416', 'alma.deoliveira@example.com', 'Sérgio Sebastião Soto Sobrinho'),
       (16, '367', 'kleon@example.com', 'Micaela Balestero Filho'),
       (17, '880', 'mário94@example.net', 'Natal Galindo Jr.'),
       (18, '163', 'gian.madeira@example.org', 'Thiago de Oliveira Urias Sobrinho'),
       (19, '442', 'alexa82@example.com', 'Srta. Julieta Beltrão Matos'),
       (20, '104', 'sdasdores@example.org', 'Jasmin Renata de Souza'),
       (21, '353', 'ftorres@example.org', 'Dr. Allison Adriana Fontes Sobrinho'),
       (22, '840', 'sdelvalle@example.com', 'Sra. Sara Ortega Sobrinho'),
       (23, '227', 'regina08@example.net', 'Tomás Dominato Jr.'),
       (24, '352', 'xreis@example.com', 'Sra. Emília Solano Estrada Filho'),
       (25, '741', 'xpedrosa@example.net', 'Valéria Andrea Quintana Filho');

INSERT INTO `veiculo`
VALUES (1, 2014, 'Kitzmann OHG mbH', 'Vicente', 'tpc - 2355', 61114171165.00, '3.92'),
       (2, 2019, 'Sorgatz e.G.', 'Willi', 'zsp - 4517', 88701015654.00, '3.55'),
       (3, 2016, 'Römer AG & Co. KG', 'Henry', 'mjo - 7711', 86225846880.00, '2.12'),
       (4, 2023, 'Rohleder', 'Giusto', 'atv - 6084', 96470528451.00, '2.8'),
       (5, 2016, 'Beckmann Wähner GmbH & Co. KGaA', 'Anatolij', 'rml - 8219', 30540764510.00, '2.13'),
       (6, 2014, 'Beier', 'Salvator', 'tbh - 6373', 98862430819.00, '3.41'),
       (7, 2023, 'Schüler', 'Jerrick', 'hbm - 9857', 68469164799.00, '2.45'),
       (8, 2018, 'Beer Ackermann OHG mbH', 'Alfonso', 'jfl - 8007', 42792936052.00, '3.83'),
       (9, 2023, 'Radisch', 'Leonard', 'sls - 0786', 24703515647.00, '3.71'),
       (10, 2019, 'Schleich GmbH & Co. KG', 'Arminio', 'qpx - 2492', 69408836134.00, '3.32'),
       (11, 2023, 'Scheibe Stiftung & Co. KGaA', 'Pedro', 'yjd - 5154', 11452980001.00, '3.53'),
       (12, 2014, 'Thanel GbR', 'Geronimo', 'xoe - 0697', 29393049277.00, '3.14'),
       (13, 2017, 'Neureuther', 'Kiran', 'njw - 3507', 32007219267.00, '3.49'),
       (14, 2016, 'Wähner GbR', 'Axel', 'pmt - 1827', 44436408990.00, '3.71'),
       (15, 2020, 'Pechel', 'Norberto', 'qde - 7373', 94801271311.00, '3.89'),
       (16, 2019, 'Putz', 'Johnny', 'ruu - 9171', 11976979866.00, '2.24'),
       (17, 2018, 'Pergande', 'Hieronymus', 'nqu - 9805', 25230085266.00, '3.74'),
       (18, 2019, 'Ruppert', 'Luke', 'ybx - 5064', 95409814519.00, '2.79'),
       (19, 2019, 'Thanel', 'Woody', 'dlo - 1133', 51587162932.00, '3.87'),
       (20, 2019, 'Bärer Bien GmbH & Co. KGaA', 'Niccolo', 'fap - 0337', 47592397717.00, '2.48'),
       (21, 2021, 'Siering', 'Guy', 'dwr - 3413', 30422852640.00, '3.15'),
       (22, 2015, 'Lachmann Weiß AG & Co. KGaA', 'Manolo', 'bxq - 2799', 93826122591.00, '2.88'),
       (23, 2020, 'Radisch', 'Veltin', 'mxq - 8212', 27984602432.00, '2.48'),
       (24, 2018, 'Gerlach AG', 'Gerard', 'eex - 1753', 66397347185.00, '2.18'),
       (25, 2022, 'Stahr', 'Florian', 'vuy - 3064', 80862993543.00, '3.77');

INSERT INTO `sede`
VALUES (1, '41220-878', 'Ferraz do Sul', 'Serrano de das Neves', 5704, 'Veritatis itaque ad corrupti ut.',
        'Rua Amélia Salas', 'BA'),
       (2, '05702-705', 'Vila Guilherme do Norte', 'Rico, Carmona e Maia', 2879,
        'Reiciendis rem magni officia rem ab dicta.', 'Travessa Rafaela', 'PI'),
       (3, '22859-099', 'Giovana do Norte', 'Cortês, Perez e de Oliveira', 6230,
        'Voluptatem ducimus sunt eius adipisci et omnis dolor consequatur.', 'Travessa Barros', 'PA'),
       (4, '94561-753', 'Micaela do Norte', 'Prado de Chaves', 2429, 'Omnis quia ab quae perspiciatis.', 'Rua Maia',
        'AP'),
       (5, '56979-263', 'Vila Suzana', 'Sandoval, Quintana e Rivera', 4252,
        'Rerum pariatur possimus perferendis consequatur minima voluptas.', 'R. Teles', 'SC'),
       (6, '25929-509', 'Santa Natália do Norte', 'Leal e de Souza', 3493,
        'Et velit magnam delectus est occaecati aut.', 'Travessa Francisco', 'MG'),
       (7, '68416-530', 'Aranda dOeste', 'Ávila,
        Oliveira e Pereira', 1689, 'Error nostrum dolorem unde doloribus vero ut eos.', 'R. Rafael', 'SC'),
       (8, '33771-300', 'Porto Diego', 'Grego,
        Cervantes e Franco', 6303, 'Non quod sed porro inventore quo aut ut.', 'Av. Emília', 'PB'),
       (9, '83121-326', 'Vila Simão', 'Neves,
        Faria e Gonçalves', 319, 'Officiis et id quod quidem earum.', 'Avenida Mateus Beltrão', 'MG'),
       (10, '33681-164', 'Lucas do Leste', 'Marinho-da Silva', 1048,
        'Dolorem ratione nesciunt maiores quis velit voluptatem.', 'Avenida Bonilha', 'PI'),
       (11, '60105-698', 'São José dOeste',
        'Valentin-Reis', 7165, 'Amet at distinctio amet aperiam omnis dignissimos similique.', 'Av. Rafaela', 'PE'),
       (12, '80314-830', 'Zambrano do Sul', 'Grego-Delatorre', 1413, 'Dolorum necessitatibus qui fuga et numquam quo.',
        'R. Gonçalves', 'DF'),
       (13, '67661-423',
        'Santa Simão dOeste', 'Serna de Velasques', 6591, 'Corporis quia fugit sequi reiciendis velit est et ut.',
        'Av. Sara Maia', 'SC'),
       (14, '87973-676', 'de Aguiar do Norte', 'Molina S. de H.', 7074, 'Labore pariatur non ut quia.',
        'Travessa Cordeiro', 'RR'),
       (15, '13297-880', 'Santa Thalissa', 'Zamana de Ferreira', 1339,
        'Aliquid omnis dolor eligendi sit rerum maiores.', 'Avenida Uchoa', 'MS'),
       (16, '90786-563', 'Pedro do Sul', 'Soares de Rangel', 1686, 'Voluptatem minima et dolor molestiae.', 'R. Fábio',
        'MA'),
       (17, '58267-397', 'das Dores dOeste',
        'Escobar de das Dores', 4992, 'Rem voluptate dolor illum doloremque aut eum maiores sed.', 'Largo Salomé',
        'MG'),
       (18, '23799-761', 'Porto Aaron', 'Uchoa e Filhos', 2804,
        'Veritatis temporibus laudantium inventore impedit aliquid qui.', 'Avenida Marinho', 'DF'),
       (19, '77872-024', 'Perez dOeste', 'Sandoval,
        Torres e Grego', 3977, 'Voluptas autem et illo dignissimos dolorem ex ea.', 'R. Cervantes', 'PR'),
       (20, '85352-964', 'Luzia do Sul', 'Batista-Solano', 4347, 'Qui cumque velit sed consectetur dolorum officia.',
        'Av. Emiliano Pereira', 'MT'),
       (21, '67721-552', 'Porto Jácomo', 'Bezerra,
        Beltrão e Serrano', 4348, 'Velit quisquam officiis quibusdam et laborum itaque in est.',
        'Travessa Guilherme Caldeira', 'PA'),
       (22, '82292-934', 'Vila Isabella', 'Prado-Galvão', 3261, 'Expedita quas mollitia exercitationem nihil.',
        'R. Dante', 'MG'),
       (23, '94942-929', 'Ávila do Sul', 'Galhardo e Rivera', 2424, 'Nobis quaerat est qui quasi quibusdam.',
        'Rua Daniel Lozano', 'RO'),
       (24, '06073-150', 'Santa Mia', 'Barros e Ortega', 1553, 'Mollitia recusandae maxime qui quisquam nam rerum.',
        'Largo Clara Queirós', 'TO'),
       (25, '05166-451', 'Marin do Leste', 'Ortiz S. de H.', 5424, 'Harum illo amet explicabo totam enim.',
        'Av. Ramires', 'PR');

INSERT INTO `material`
VALUES (1, 'Perferendis corporis est omnis corporis voluptas saepe incidunt.', 'earum'),
       (2, 'Esse consequatur delectus et et dolorum.', 'neque'),
       (3, 'Tempore praesentium fugiat dolores magni tenetur porro fugiat.', 'dolores'),
       (4, 'At quia molestiae voluptate est.', 'reiciendis'),
       (5, 'Sit omnis ut ipsam veniam accusamus nihil dolore.', 'ipsum'),
       (6, 'Deserunt ratione ipsa voluptas cumque et consectetur culpa.', 'in'),
       (7, 'Quo ipsum maxime recusandae numquam laboriosam reiciendis.', 'omnis'),
       (8, 'Aut ipsa fuga eum sed facilis.', 'ut'),
       (9, 'A rem corporis facilis consequatur qui vel enim ut.', 'nobis'),
       (10, 'Soluta perspiciatis vel necessitatibus est ea commodi.', 'nihil'),
       (11, 'Facilis impedit porro doloremque rerum exercitationem.', 'eos'),
       (12, 'Aperiam eos sapiente dolores omnis cupiditate magni nam.', 'sit'),
       (13, 'Voluptatem omnis est dolor autem neque accusantium.', 'consequatur'),
       (14, 'Magnam molestiae quis quidem facere architecto magnam deserunt ipsum.', 'corrupti'),
       (15, 'Ipsam ratione ab laudantium quas dolore aut voluptate distinctio.', 'earum'),
       (16, 'Consectetur expedita officiis necessitatibus molestiae deleniti hic saepe.', 'itaque'),
       (17, 'Unde quas praesentium voluptatum corporis sint vitae facilis.', 'et'),
       (18, 'Labore rerum non dolores necessitatibus a sequi doloremque.', 'eum'),
       (19, 'Eaque saepe voluptas hic magni deleniti voluptatem et.', 'numquam'),
       (20, 'Qui voluptates id quo quia a sed.', 'rerum'),
       (21, 'Ullam quia qui reiciendis consequatur blanditiis.', 'unde'),
       (22, 'Rerum consectetur quia quia sed reiciendis sed.', 'voluptates'),
       (23, 'Corporis inventore atque et dolor eaque.', 'sed'),
       (24, 'Ratione aut ut similique sint aliquid et.', 'corrupti'),
       (25, 'Voluptates dolorem consequuntur illum est dignissimos provident asperiores.', 'hic'),
       (26, 'Consequatur assumenda quisquam culpa aliquam ut et.', 'quia'),
       (27, 'Aspernatur doloribus delectus eum provident.', 'dolorem'),
       (28, 'Perferendis laboriosam cumque nemo nulla dolores non voluptates.', 'nihil'),
       (29, 'Veniam reprehenderit dolorem debitis dolores quaerat quia.', 'ut'),
       (30, 'Sapiente quos perferendis dicta ut recusandae.', 'delectus'),
       (31, 'Blanditiis veritatis soluta tenetur qui.', 'repellendus'),
       (32, 'Voluptatibus quis rerum tenetur eveniet unde alias ipsam excepturi.', 'libero'),
       (33, 'Dolores rerum voluptatem quisquam velit.', 'vero'),
       (34, 'Qui minus magni neque quis similique nostrum ut.', 'non'),
       (35, 'Error nam in eius quo minima hic cumque.', 'maiores'),
       (36, 'Consectetur magni eligendi perspiciatis laudantium veniam eligendi.', 'totam'),
       (37, 'Explicabo exercitationem molestiae qui perspiciatis.', 'quam'),
       (38, 'Deserunt placeat aut sequi laudantium aut.', 'quos'),
       (39, 'Et qui dolorem neque alias sit eos nostrum.', 'ullam'),
       (40, 'Est dolorem odio illo et sit.', 'qui'),
       (41, 'Reiciendis accusamus eligendi minima cupiditate facere.', 'voluptas'),
       (42, 'Asperiores architecto beatae aliquid.', 'voluptatem'),
       (43, 'Sunt quis id minus perferendis aliquid corporis.', 'corporis'),
       (44, 'Temporibus beatae voluptas quia distinctio et.', 'voluptatem'),
       (45, 'Autem reiciendis deserunt ipsam suscipit earum accusamus.', 'veniam'),
       (46, 'Omnis non ipsa earum enim asperiores cum aut.', 'perferendis'),
       (47, 'Perspiciatis ullam nisi voluptatibus similique quasi quisquam.', 'ratione'),
       (48, 'At minus et sed qui.', 'odit'),
       (49, 'Error voluptates quasi illum debitis.', 'enim'),
       (50, 'Dolorem enim sed ducimus non nesciunt harum.', 'quia'),
       (51, 'Et hic culpa doloribus iste et.', 'ut'),
       (52, 'Voluptatem voluptates aspernatur pariatur.', 'perspiciatis'),
       (53, 'Ipsum et inventore blanditiis tempore animi eos.', 'harum'),
       (54, 'Ab modi vel aperiam amet praesentium.', 'facere'),
       (55, 'Alias illum vel cupiditate id eos sint assumenda non.', 'tempora'),
       (56, 'Impedit est eos voluptatem voluptas sed architecto eius.', 'iusto'),
       (57, 'Velit praesentium perferendis quia eveniet sunt consequatur.', 'quia'),
       (58, 'Rem doloribus sunt accusamus laudantium ipsam ipsam qui repellendus.', 'itaque'),
       (59, 'Sed et doloremque dicta ea.', 'fuga'),
       (60, 'Consequatur nihil in et facilis modi suscipit delectus.', 'consequatur'),
       (61, 'Voluptatem natus rerum possimus soluta et.', 'repudiandae'),
       (62, 'Expedita perferendis sit facere rerum.', 'numquam'),
       (63, 'Consequatur et sequi aut minima.', 'excepturi'),
       (64, 'Dolores ab est voluptates et aut ad quas.', 'nihil'),
       (65, 'In iure dicta laboriosam beatae dolorum in molestiae.', 'magni'),
       (66, 'Aut maxime ex deserunt exercitationem tenetur non earum.', 'error'),
       (67, 'Dolores dolor consectetur totam et voluptatibus optio.', 'aperiam'),
       (68, 'Ab eveniet voluptatem error aut nisi fugiat.', 'consectetur'),
       (69, 'Quod excepturi qui odio.', 'quaerat'),
       (70, 'Autem non explicabo neque.', 'cum'),
       (71, 'Tempore amet ut itaque odit aut alias sed.', 'amet'),
       (72, 'Fugit consectetur aut enim corrupti.', 'eius'),
       (73, 'Ratione unde et quibusdam.', 'fugiat'),
       (74, 'Eius vitae nihil officia voluptatem ab at assumenda libero.', 'tenetur'),
       (75, 'Voluptatum corrupti corporis id laboriosam exercitationem at.', 'cupiditate'),
       (76, 'Fuga nam nisi saepe minima.', 'nisi'),
       (77, 'Totam maxime explicabo dolor.', 'est'),
       (78, 'Numquam quis quia impedit unde.', 'rem'),
       (79, 'Animi temporibus distinctio quos alias natus.', 'voluptatem'),
       (80, 'Aspernatur eius velit repellat velit incidunt.', 'iusto'),
       (81, 'Consequuntur non enim blanditiis laudantium ad aliquid et sint.', 'ducimus'),
       (82, 'Est qui molestiae commodi impedit ea repudiandae voluptas corrupti.', 'vel'),
       (83, 'Minima ullam assumenda iusto corrupti eos doloribus vitae.', 'qui'),
       (84, 'Sit delectus nesciunt voluptatibus omnis sequi accusamus sit facilis.', 'voluptatibus'),
       (85, 'Iusto odio sed esse quia est.', 'rerum'),
       (86, 'Ipsa consequatur exercitationem suscipit saepe eos voluptatum voluptate iure.', 'sunt'),
       (87, 'Rerum itaque consequuntur odio qui temporibus qui et.', 'voluptatibus'),
       (88, 'Nostrum officia ipsa eligendi sint.', 'facere'),
       (89, 'Et architecto dolores doloribus laboriosam maxime tempore error.', 'et'),
       (90, 'Eos atque cumque placeat praesentium magnam non.', 'quam'),
       (91, 'Ipsa placeat voluptates incidunt earum odio hic.', 'repellat'),
       (92, 'Eos fugit quo incidunt cumque.', 'perferendis'),
       (93, 'Rem ex quidem omnis ea quis occaecati et voluptatem.', 'nesciunt'),
       (94, 'Dignissimos expedita excepturi doloribus aut.', 'at'),
       (95, 'Distinctio eos eaque consectetur iure eum.', 'voluptas'),
       (96, 'Et corporis debitis quia tempora vero et adipisci.', 'cum'),
       (97, 'Culpa labore consequatur minus occaecati a consequuntur consequatur.', 'et'),
       (98, 'Vitae voluptas autem modi doloribus molestiae temporibus.', 'sint'),
       (99, 'Molestias alias debitis aut ex ea dolore beatae.', 'laudantium'),
       (100, 'Atque deleniti voluptates magnam mollitia nemo.', 'rerum');
