spring:
  application:
    name: api-transporte-service
  profiles:
    active: ${ACTIVE_PROFILE:default}
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client-name: api-transportes-client
      resourceserver:
        jwt:
          trusted-issuers: http://localhost/realms/api-transportes
          jwk-set-uri: http://localhost/realms/api-transportes/protocol/openid-connect/certs
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus,*"
      discovery:
        enabled: true
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
server:
  port: 8080
