spring:
  application:
    name: api-transporte-service
  profiles:
    active: default
  flyway:
    enabled: false
    locations: classpath:/db/migration
    baseline-on-migrate: true
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus,*"
      discovery:
        enabled: true
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
server:
  port: 8080
