spring:
  application:
    name: api-transporte-service
  security:
    oauth2:
      client-name: ${CLIENT_NAME}
      resourceserver:
        jwt:
          trusted-issuers: ${TRUSTED_ISSUERS}
        jwk-set-uri: ${JWK_SET_URI}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: ${ACTIVE_PROFILE:default}
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database: ${DB_VENDOR}
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus,*"
      discovery:
        enabled: true
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
server:
  port: ${SERVER_PORT:8080}
