openapi: 3.0.0

info:
  version: "1.0.0"
  title: Api-Transportes

tags:
  - name: "Sedes"
    description: "Descreve os endpoints para o gerenciamento das Sedes"
  - name: "Veiculos"
    description: "Descreve os endpoints para o gerenciamento dos Veiculos"
  - name: "Motoristas"
    description: "Descreve os endpoints para o gerenciamento dos Motoristas"
  - name: "Viagens"
    description: "Descreve os endpoints para o gerenciamento das Viagens"
  - name: "Destinos"
    description: "Descreve os endpoints para o gerenciamento dos Destinos"

servers:
  - url: "http://localhost:8080/"
    description: "Desenvolvimento local"

paths:
  /sedes:
    post:
      operationId: "criarSede"
      summary: "criarSede"
      description: "Cria uma sede com base nos dados fornecidos."
      tags:
        - Sedes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSede'
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sede'
    get:
      description: "Lista todas as sedes ordenadas por ID."
      summary: listaTodasAsSedes
      operationId: listaTodasAsSedes
      tags:
        - Sedes
      responses:
        200:
          description: "Lista de Sedes ordenadas por ID."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sede'
  /sedes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: "O ID da sede que se deseja editar ou excluir"
        schema:
          type: string
    put:
      operationId: "editarSede"
      summary: "editarSede"
      description: "Altera uma sede com base nos dados fornecidos."
      tags:
        - Sedes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSede'
      responses:
        201:
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sede'
    delete:
      description: "Exclui o registro de uma sede específica."
      summary: excluirSede
      operationId: excluirSede
      tags:
        - Sedes
      responses:
        200:
          description: "Deleted"
        400:
          description: "Id inválido"
    get:
      description: "Devolve uma sede específica, selecionando-a pelo seu ID."
      summary: trazSedePorId
      operationId: trazSedePorId
      tags:
        - Sedes
      responses:
        200:
          description: "Devolve uma sede específica buscando por ID."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sede'

  /motoristas:
    post:
      operationId: criarMotorista
      summary: criarMotorista
      description: "Cria um motorista com base nos dados fornecidos."
      tags:
        - Motoristas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtributosMotorista'
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motorista'
    get:
      description: "Lista todos os motoristas ordenados por ID."
      summary: listaTodosMotoristas
      operationId: listaTodosMotoristas
      tags:
        - Motoristas
      responses:
        200:
          description: "Lista dos motoristas ordenados por ID."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Motorista'
  /motoristas/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: "O ID do motorista que se deseja editar ou excluir"
        schema:
          type: string
    put:
      operationId: editarMotorista
      summary: editarMotorista
      description: "Altera o cadastro de um motorista com base no seu ID e nos dados fornecidos."
      tags:
        - Motoristas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtributosMotorista'
      responses:
        201:
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motorista'
    delete:
      description: "Exclui o registro de um motorista específico."
      summary: excluirMotorista
      operationId: excluirMotorista
      tags:
        - Motoristas
      responses:
        200:
          description: "Deleted"
        400:
          description: "Id inválido"
    get:
      description: "Devolve um motorista específico, selecionando-o pelo seu ID."
      summary: trazMotoristaPorId
      operationId: trazMotoristaPorId
      tags:
        - Motoristas
      responses:
        200:
          description: "Devolve um motorista específico buscando por ID."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motorista'

  /veiculos:
    post:
      operationId: criarVeiculo
      summary: criarVeiculo
      description: "Cria um veículo com base nos dados fornecidos."
      tags:
        - Veiculos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertVeiculo'
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veiculo'
    get:
      description: "Lista todos os veiculos ordenados por ID."
      summary: listaTodosVeiculos
      operationId: listaTodosVeiculos
      tags:
        - Veiculos
      responses:
        200:
          description: "Lista dos veiculos ordenados por ID."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veiculo'
  /veiculos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: "O ID do veiculo que se deseja editar ou excluir"
        schema:
          type: string
    put:
      operationId: editarVeiculo
      summary: editarVeiculo
      description: "Altera o cadastro de um veiculo com base no seu ID e nos dados fornecidos."
      tags:
        - Veiculos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertVeiculo'
      responses:
        201:
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veiculo'
    delete:
      description: "Exclui o registro de um veículo específico."
      summary: excluirVeiculo
      operationId: excluirVeiculo
      tags:
        - Veiculos
      responses:
        200:
          description: "Deleted"
        400:
          description: "Id inválido"
    get:
      description: "Devolve um veículo específico, selecionando-o pelo seu ID."
      summary: trazVeiculoPorId
      operationId: trazVeiculoPorId
      tags:
        - Veiculos
      responses:
        200:
          description: "Devolve um veiculo específico buscando por ID."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Veiculo'

components:
  schemas:

    Endereco:
      type: object
      properties:
        rua:
          type: string
          description: "Nome da rua onde a sede está localizada"
          example: "Rua dos Bobos"
        numero:
          type: integer
          description: "Número, complemento à rua"
          example: "1015"
        cep:
          type: string
          description: "CEP da localidade."
          pattern: '\d{5}\-\d{3}'
        cidade:
          type: string
          description: "Nome da cidade onde a sede está localizada"
          example: "Tijucas"
        uf:
          $ref: '#/components/schemas/Uf'
          example: "SC"
      required:
        - rua
        - numero
        - cep
        - cidade
        - uf
    Uf:
      type: string
      enum:
        - RO
        - AC
        - AM
        - RR
        - PA
        - AP
        - TO
        - MA
        - PI
        - CE
        - RN
        - PB
        - PE
        - AL
        - SE
        - BA
        - MG
        - ES
        - RJ
        - SP
        - PR
        - SC
        - RS
        - MS
        - MT
        - GO
        - DF

    AtributosSede:
      type: object
      properties:
        nome:
          type: string
          description: "Nome da sede ou referência à esta sede especificamente."
          example: "DPE 01 - Criciuma."
        observacao:
          type: string
          description: "Uma descrição sobre a sede, ponto de referência ou outra observação qualquer."
          example: "Na Avenida Brasil, depois do shopping ABC."
      required:
        - nome
        - observacao

    UpsertSede:
      allOf:
        - $ref: '#/components/schemas/Endereco'
        - $ref: '#/components/schemas/AtributosSede'

    Sede:
      allOf:
        - $ref: '#/components/schemas/UpsertSede'
        - type: object
          properties:
            id:
              type: integer
              description: "Atributo que identifica cada sede de maneira única."
              example: "56"


    AtributosMotorista:
      type: object
      properties:
        nome:
          type: string
          description: "Nome do motorista."
          example: "João da Silva"
        carteira:
          type: string
          description: "Numero da carteira de motorista."
          pattern: '\d{11}'
          example: "63365478917"
        email:
          type: string
          description: "Email do motorista."
          format: email
      required:
        - nome
        - carteira
        - email

    UpsertMotorista:
      allOf:
        - $ref: '#/components/schemas/AtributosMotorista'

    Motorista:
      allOf:
        - $ref: '#/components/schemas/AtributosMotorista'
        - type: object
          properties:
            id:
              type: integer
              description: "Atributo que identifica cada motorista de maneira única."
              example: "22"


    AtributosVeiculo:
      type: object
      properties:
        modelo:
          type: string
          description: "Modelo do veículo."
          example: "Hyundai HR Baú"
        marca:
          type: string
          description: "Marca da montadora do veículo."
          example: "Hyundai"
        placa:
          type: string
          description: "Placa do veículo, atributo único."
          pattern: '[A-Z]{3}\d{4}'
        ano:
          type: integer
          description: "Ano de fabricação do veículo."
          example: "2020"
        renavan:
          type: number
          description: "Número de identificação do veículo."
          example: "3214569871"
          pattern: '\d{10}'
        tamanho:
          type: string
          description: "Tamanho do veículo."
          example: "3,58m"
      required:
        - modelo
        - marca
        - placa
        - ano
        - renavan
        - tamanho

    UpsertVeiculo:
      allOf:
        - $ref: '#/components/schemas/AtributosVeiculo'

    Veiculo:
      allOf:
        - $ref: '#/components/schemas/UpsertVeiculo'
        - type: object
          properties:
            id:
              type: integer
              description: "Atributo que identifica cada veículo de maneira única."
              example: "102"


    Transporte:
      type: object
      description: "Todas as informações de uma viagem"
      properties:
        motoristaId:
          type: integer
          description: "Id único que identifica o motorista desta viagem."
        veiculoId:
          type: integer
          description: "Id único que identifica o veiculo usado nesta viagem."
        paradas:
          type: array
          items:
            $ref: '#/components/schemas/Destino'
        dataSaida:
          type: string
          description: "Data de partida da viagem."
        horaDeSaida:
          type: string
          description: "Hora programada para partida da viagem."
        dataChegada:
          type: string
          description: "Data prevista para a chegada de volta no armazém central."
        horaDeChegada:
          type: string
          description: "Hora prevista para a chegada de volta no armazém central."

    Destino:
      type: object
      description: "Sede por onde o transporte deve passar e a lista de itens que ele deve deixar neste destino."
      properties:
        sedeId:
          type: integer
          description: "Id da sede para onde devem ir os materiais transportados"
        materiais:
          type: array
          items:
            $ref: '#/components/schemas/Material'
        status:
          type: string
          enum:
            - CONFIRMADO
            - NAO_CONFIRMADO

    Material:
      type: object
      description: "Material que será levado ao destino."
      properties:
        nome:
          type: object
          description: "Nome do produto em questão."
        descricao:
          type: string
          description: "Descricao do material a ser transportado."
          example: "Malote de socumentos"
        setor:
          type: string
          description: "Setor"

  responses:
    400:
      description: "Algo de errado aconteceu com a requisicao."
    403:
      description: "Este usuário não tem permissões para executar esta ação."

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: [ ]
